#!/usr/bin/env bash
export RAW_DATA_SOURCE='capstone'
export PREPROCESSING_DATA_SOURCE='capstone_preprocessing'
export MERGE_DATA_TARGET='capstone_merge'
export TRAIN_DATA_TARGET='capstone_train'

pipenv install --dev --python 3.9.5
pipenv run python3 fetch_data.py
pipenv run python3 preprocessing.py

pipenv run python3 fill_na.py
pipenv run python3 prepare_training.py --merge_data ${MERGE_DATA_TARGET} --model_base ${TRAIN_DATA_TARGET}
./shell/build.sh
./shell/copy_hdfs.sh
./shell/submitPreprocessing.sh ${RAW_DATA_SOURCE} ${PREPROCESSING_DATA_SOURCE}
./shell/submitMerge.sh ${PREPROCESSING_DATA_SOURCE} ${MERGE_DATA_TARGET}
# generated by prepare_training.py
chmod +x ./shell/submitTrainingJobs.sh
./shell/submitTrainingJobs.sh