#!/usr/bin/env bash
./shell/submitTraining.sh capstone_merge/2020_Age.parquet capstone_train/2020_Age.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Age1stCode.parquet capstone_train/2020_Age1stCode.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_CompFreq.parquet capstone_train/2020_CompFreq.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_CompTotal.parquet capstone_train/2020_CompTotal.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Country.parquet capstone_train/2020_Country.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_CurrencyDesc.parquet capstone_train/2020_CurrencyDesc.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_CurrencySymbol.parquet capstone_train/2020_CurrencySymbol.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_DatabaseDesireNextYear.parquet capstone_train/2020_DatabaseDesireNextYear.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_DatabaseWorkedWith.parquet capstone_train/2020_DatabaseWorkedWith.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_DevType.parquet capstone_train/2020_DevType.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_EdLevel.parquet capstone_train/2020_EdLevel.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Employment.parquet capstone_train/2020_Employment.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Ethnicity.parquet capstone_train/2020_Ethnicity.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Gender.parquet capstone_train/2020_Gender.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Hobbyist.parquet capstone_train/2020_Hobbyist.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_JobFactors.parquet capstone_train/2020_JobFactors.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_JobSat.parquet capstone_train/2020_JobSat.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_JobSeek.parquet capstone_train/2020_JobSeek.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_LanguageDesireNextYear.parquet capstone_train/2020_LanguageDesireNextYear.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_LanguageWorkedWith.parquet capstone_train/2020_LanguageWorkedWith.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_MainBranch.parquet capstone_train/2020_MainBranch.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_MiscTechDesireNextYear.parquet capstone_train/2020_MiscTechDesireNextYear.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_MiscTechWorkedWith.parquet capstone_train/2020_MiscTechWorkedWith.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWCollabToolsDesireNextYear.parquet capstone_train/2020_NEWCollabToolsDesireNextYear.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWCollabToolsWorkedWith.parquet capstone_train/2020_NEWCollabToolsWorkedWith.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWDevOps.parquet capstone_train/2020_NEWDevOps.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWDevOpsImpt.parquet capstone_train/2020_NEWDevOpsImpt.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWEdImpt.parquet capstone_train/2020_NEWEdImpt.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWJobHunt.parquet capstone_train/2020_NEWJobHunt.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWJobHuntResearch.parquet capstone_train/2020_NEWJobHuntResearch.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWLearn.parquet capstone_train/2020_NEWLearn.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWOffTopic.parquet capstone_train/2020_NEWOffTopic.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWOnboardGood.parquet capstone_train/2020_NEWOnboardGood.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWOtherComms.parquet capstone_train/2020_NEWOtherComms.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWOvertime.parquet capstone_train/2020_NEWOvertime.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWPurchaseResearch.parquet capstone_train/2020_NEWPurchaseResearch.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWPurpleLink.parquet capstone_train/2020_NEWPurpleLink.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWSOSites.parquet capstone_train/2020_NEWSOSites.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_NEWStuck.parquet capstone_train/2020_NEWStuck.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_OpSys.parquet capstone_train/2020_OpSys.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_OrgSize.parquet capstone_train/2020_OrgSize.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_PlatformDesireNextYear.parquet capstone_train/2020_PlatformDesireNextYear.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_PlatformWorkedWith.parquet capstone_train/2020_PlatformWorkedWith.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_PurchaseWhat.parquet capstone_train/2020_PurchaseWhat.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_SOAccount.parquet capstone_train/2020_SOAccount.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_SOComm.parquet capstone_train/2020_SOComm.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_SOPartFreq.parquet capstone_train/2020_SOPartFreq.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_SOVisitFreq.parquet capstone_train/2020_SOVisitFreq.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Sexuality.parquet capstone_train/2020_Sexuality.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_SurveyEase.parquet capstone_train/2020_SurveyEase.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_SurveyLength.parquet capstone_train/2020_SurveyLength.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_Trans.parquet capstone_train/2020_Trans.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_UndergradMajor.parquet capstone_train/2020_UndergradMajor.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_WebframeDesireNextYear.parquet capstone_train/2020_WebframeDesireNextYear.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_WebframeWorkedWith.parquet capstone_train/2020_WebframeWorkedWith.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_WelcomeChange.parquet capstone_train/2020_WelcomeChange.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_WorkWeekHrs.parquet capstone_train/2020_WorkWeekHrs.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_YearsCode.parquet capstone_train/2020_YearsCode.model capstone-1.0.0-uberjar.jar & 
./shell/submitTraining.sh capstone_merge/2020_YearsCodePro.parquet capstone_train/2020_YearsCodePro.model capstone-1.0.0-uberjar.jar & 
